const products: (Cake | Dessert)[] = [
  // Cakes (7 items)
  {
    id: "cake001",
    name: "Classic Chocolate Layer Cake",
    selector_ref: "shadow_cake_8",
    type: "CAKE",
    characteristics: {
      type: "BIRTHDAY",
      size: ["6-inch", "8-inch", "10-inch"],
      flavor: ["Chocolate", "Vanilla"],
      filling: ["Chocolate Ganache", "Vanilla Cream"],
      frosting: ["Chocolate Buttercream", "Whipped Cream"],
      topping: ["Chocolate Shavings", "Sprinkles"],
    },
    header: "Rich Chocolate Delight",
    description: "A moist chocolate cake layered with creamy filling and topped with your choice of frosting.",
    indications: "Best served chilled.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/chocolate_cake.jpeg",
  },
  {
    id: "cake002",
    name: "Vanilla Wedding Cake",
    selector_ref: "shadow_cake_5",
    type: "CAKE",
    characteristics: {
      type: "WEDDING",
      size: ["8-inch", "10-inch", "12-inch"],
      flavor: ["Vanilla", "Almond"],
      filling: ["Buttercream", "Raspberry Jam"],
      frosting: ["Vanilla Fondant", "Swiss Meringue"],
      topping: ["Edible Flowers", "Pearl Sprinkles"],
    },
    header: "Elegant Wedding Bliss",
    description: "A sophisticated vanilla cake perfect for weddings, adorned with delicate toppings.",
    indications: "Store at room temperature.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: false, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/vanilla_wedding_cake.jpeg",
  },
  {
    id: "cake003",
    name: "Red Velvet Celebration Cake",
    selector_ref: "shadow_cake_7",
    type: "CAKE",
    characteristics: {
      type: "BIRTHDAY",
      size: ["6-inch", "8-inch"],
      flavor: ["Red Velvet"],
      filling: ["Cream Cheese", "Vanilla Custard"],
      frosting: ["Cream Cheese Frosting"],
      topping: ["Red Velvet Crumbs", "White Chocolate Curls"],
    },
    header: "Velvety Indulgence",
    description: "A rich red velvet cake with a tangy cream cheese filling and frosting.",
    indications: "Keep refrigerated.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/red_velvet.avif",
  },
  {
    id: "cake004",
    name: "Lemon Chiffon Cake",
    selector_ref: "shadow_cake_6",
    type: "CAKE",
    characteristics: {
      type: "GRADUATION",
      size: ["8-inch", "10-inch"],
      flavor: ["Lemon"],
      filling: ["Lemon Curd"],
      frosting: ["Lemon Buttercream", "Whipped Cream"],
      topping: ["Candied Lemon Peel", "Powdered Sugar"],
    },
    header: "Zesty Celebration",
    description: "A light and fluffy lemon cake with a refreshing curd filling.",
    indications: "Serve at room temperature.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: true },
    image_ref: "/public/test/carrot_cake.jpeg",
  },
  {
    id: "cake005",
    name: "Carrot Cake",
    selector_ref: "shadow_cake_6",
    type: "CAKE",
    characteristics: {
      type: "OTHER",
      size: ["6-inch", "9-inch"],
      flavor: ["Carrot", "Spice"],
      filling: ["Cream Cheese"],
      frosting: ["Cream Cheese Frosting"],
      topping: ["Chopped Walnuts", "Carrot Curls"],
    },
    header: "Spiced Comfort",
    description: "A moist carrot cake with warm spices and a creamy frosting.",
    indications: "Store in a cool place.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: false, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/carrot_cake.jpeg",
  },
  {
    id: "cake006",
    name: "Chocolate Lava Cake",
    selector_ref: "shadow_cake_8",
    type: "CAKE",
    characteristics: {
      type: "OTHER",
      size: ["Individual", "6-inch"],
      flavor: ["Chocolate"],
      filling: ["Molten Chocolate"],
      frosting: ["None"],
      topping: ["Powdered Sugar", "Berries"],
    },
    header: "Molten Bliss",
    description: "A warm chocolate cake with a gooey center, perfect for chocolate lovers.",
    indications: "Serve warm.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/chocolate_cake.jpeg",
  },
  {
    id: "cake007",
    name: "Baby Blue Tiered Cake",
    selector_ref: "shadow_cake_5",
    type: "CAKE",
    characteristics: {
      type: "BABY_SHOWER",
      size: ["8-inch", "10-inch"],
      flavor: ["Vanilla", "Blueberry"],
      filling: ["Blueberry Compote", "Vanilla Cream"],
      frosting: ["Blue Buttercream"],
      topping: ["Fondant Stars", "Edible Pearls"],
    },
    header: "Sweet Baby Blues",
    description: "A charming tiered cake for baby showers with soft blue hues.",
    indications: "Keep refrigerated.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/red_velvet.avif",
  },

  // Desserts (13 items)
  {
    id: "dessert001",
    name: "Chocolate Chip Cookies",
    selector_ref: "shadow_cake_3",
    type: "DESSERT",
    characteristics: {
      type: "OTHER",
      size: ["Small", "Large"],
      flavor: ["Chocolate", "Vanilla"],
      filling: ["None"],
      frosting: ["None"],
      topping: ["Chocolate Chips"],
    },
    header: "Classic Cookie Crunch",
    description: "Chewy cookies packed with chocolate chips.",
    indications: "Store in an airtight container.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/chocolate_chips_cookies.webp",
  },
  {
    id: "dessert002",
    name: "Vanilla Cupcakes",
    type: "DESSERT",
    selector_ref: "shadow_cake_2", // Reusing since we ran out of unique refs
    characteristics: {
      type: "BIRTHDAY",
      size: ["Standard", "Mini"],
      flavor: ["Vanilla"],
      filling: ["None"],
      frosting: ["Vanilla Buttercream"],
      topping: ["Sprinkles", "Edible Glitter"],
    },
    header: "Simple Sweetness",
    description: "Light vanilla cupcakes with creamy frosting.",
    indications: "Best within 2 days.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/cupackes.jpg",
  },
  {
    id: "dessert003",
    name: "Apple Pie",
    type: "DESSERT",
    selector_ref: "shadow_cake_4",
    characteristics: {
      type: "OTHER",
      size: ["8-inch", "Individual"],
      flavor: ["Apple", "Cinnamon"],
      filling: ["Spiced Apple"],
      frosting: ["None"],
      topping: ["Lattice Crust", "Sugar Dusting"],
    },
    header: "Homestyle Comfort",
    description: "A classic apple pie with a flaky crust.",
    indications: "Serve warm with ice cream.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/apple_pie.jpeg",
  },
  {
    id: "dessert004",
    name: "Lemon Bars",
    type: "DESSERT",
    selector_ref: "shadow_cake_3",
    characteristics: {
      type: "OTHER",
      size: ["Small Square", "Large Square"],
      flavor: ["Lemon"],
      filling: ["Lemon Curd"],
      frosting: ["None"],
      topping: ["Powdered Sugar"],
    },
    header: "Tangy Treats",
    description: "Buttery shortbread topped with zesty lemon curd.",
    indications: "Store refrigerated.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/cupcakes.jpeg",
  },
  {
    id: "dessert005",
    name: "Red Velvet Cupcakes",
    type: "DESSERT",
    selector_ref: "shadow_cake_2",
    characteristics: {
      type: "BIRTHDAY",
      size: ["Standard", "Mini"],
      flavor: ["Red Velvet"],
      filling: ["Cream Cheese"],
      frosting: ["Cream Cheese Frosting"],
      topping: ["Red Crumbs"],
    },
    header: "Velvet Bites",
    description: "Mini red velvet cakes with creamy frosting.",
    indications: "Keep cool.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/cupcakes.jpeg",
  },
  {
    id: "dessert006",
    name: "Peanut Butter Cookies",
    type: "DESSERT",
    selector_ref: "shadow_cake_3",
    characteristics: {
      type: "OTHER",
      size: ["Small", "Large"],
      flavor: ["Peanut Butter"],
      filling: ["None"],
      frosting: ["None"],
      topping: ["Crosshatch Pattern"],
    },
    header: "Nutty Goodness",
    description: "Rich peanut butter cookies with a classic design.",
    indications: "Store in a cool, dry place.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: false, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/brownie_bites.jpeg",
  },
  {
    id: "dessert007",
    name: "Pumpkin Pie",
    type: "DESSERT",
    selector_ref: "shadow_cake_4",
    characteristics: {
      type: "OTHER",
      size: ["8-inch", "Individual"],
      flavor: ["Pumpkin", "Spice"],
      filling: ["Pumpkin Custard"],
      frosting: ["None"],
      topping: ["Whipped Cream"],
    },
    header: "Autumn Delight",
    description: "A spiced pumpkin pie with a smooth, creamy filling.",
    indications: "Serve chilled or at room temp.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/pumpkin_pie.jpg",
  },
  {
    id: "dessert008",
    name: "Brownie Bites",
    type: "DESSERT",
    selector_ref: "shadow_cake_1",
    characteristics: {
      type: "OTHER",
      size: ["Bite-sized", "Square"],
      flavor: ["Chocolate"],
      filling: ["None"],
      frosting: ["None"],
      topping: ["Powdered Sugar", "Walnuts"],
    },
    header: "Fudgy Morsels",
    description: "Rich, chewy brownies in bite-sized portions.",
    indications: "Store in an airtight container.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: false, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/brownie_bites.jpeg",
  },
  {
    id: "dessert009",
    name: "Strawberry Shortcake",
    type: "DESSERT",
    selector_ref: "shadow_cake_1",
    characteristics: {
      type: "OTHER",
      size: ["Individual"],
      flavor: ["Vanilla"],
      filling: ["Strawberry", "Whipped Cream"],
      frosting: ["None"],
      topping: ["Fresh Strawberries"],
    },
    header: "Berry Bliss",
    description: "Light sponge cake layered with strawberries and cream.",
    indications: "Serve fresh.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/cupcakes.jpeg",
  },
  {
    id: "dessert010",
    name: "Oatmeal Raisin Cookies",
    type: "DESSERT",
    selector_ref: "shadow_cake_3",
    characteristics: {
      type: "OTHER",
      size: ["Small", "Large"],
      flavor: ["Oatmeal", "Cinnamon"],
      filling: ["None"],
      frosting: ["None"],
      topping: ["Raisins"],
    },
    header: "Hearty Classics",
    description: "Chewy oatmeal cookies with sweet raisins.",
    indications: "Store in a cool place.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/chocolate_chips_cookies.webp",
  },
  {
    id: "dessert011",
    name: "Key Lime Pie",
    type: "DESSERT",
    selector_ref: "shadow_cake_4",
    characteristics: {
      type: "OTHER",
      size: ["8-inch", "Individual"],
      flavor: ["Lime"],
      filling: ["Key Lime Custard"],
      frosting: ["None"],
      topping: ["Whipped Cream", "Lime Zest"],
    },
    header: "Tropical Tang",
    description: "A tart and creamy key lime pie with a graham crust.",
    indications: "Keep refrigerated.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/apple_pie.jpeg",
  },
  {
    id: "dessert012",
    name: "Salted Caramel Cupcakes",
    type: "DESSERT",
    selector_ref: "shadow_cake_2",
    characteristics: {
      type: "GRADUATION",
      size: ["Standard", "Mini"],
      flavor: ["Caramel", "Vanilla"],
      filling: ["Caramel"],
      frosting: ["Salted Caramel Buttercream"],
      topping: ["Sea Salt Flakes"],
    },
    header: "Sweet & Salty",
    description: "Vanilla cupcakes with a caramel core and salty frosting.",
    indications: "Best fresh.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: true, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/cupcakes.jpeg",
  },
  {
    id: "dessert013",
    name: "Pecan Pie Bars",
    type: "DESSERT",
    selector_ref: "shadow_cake_3",
    characteristics: {
      type: "OTHER",
      size: ["Small Square", "Large Square"],
      flavor: ["Pecan", "Caramel"],
      filling: ["Pecan Caramel"],
      frosting: ["None"],
      topping: ["Toasted Pecans"],
    },
    header: "Nutty Caramel Crunch",
    description: "Rich pecan pie filling on a shortbread base.",
    indications: "Store at room temperature.",
    options: { isVegan: false, isGlutenFree: false, isDairyFree: false, isNutFree: false, isSoyFree: true, isEggFree: false, isSugarFree: false, isLowFat: false },
    image_ref: "/public/test/apple_pie.jpeg",
  },
];

export default products;
