name: Deploy to SSH server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Add host key to known host
      run: ssh-keyscan -p 65002 145.14.151.58 >> ~/.ssh/known_hosts
    - name: Deploy
      run: |
        scp -P 65002 -r dist/* u996714911@145.14.151.58:/domains/lanonnarose.com/public_html/
